# Generated by Django 3.2.25 on 2025-04-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrowsingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('query', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
