# Generated by Django 3.2.25 on 2025-04-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='browsinghistory',
            name='time_spent',
            field=models.FloatField(default=0.0, help_text='Time spent in seconds'),
        ),
    ]
