# Generated by Django 3.2.25 on 2025-04-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_browsinghistory_time_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browsinghistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
