# Generated by Django 3.2.25 on 2025-04-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_browsinghistory_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='browsinghistory',
            name='mental_state',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
