# Generated by Django 3.2.25 on 2025-04-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_browsinghistory_mental_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='browsinghistory',
            name='sentiment_score',
            field=models.FloatField(default=0.0),
        ),
    ]
