# Generated by Django 3.2.25 on 2025-04-18 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20250418_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertcontrol',
            name='reset_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
